## cheetah-dir
envs: cheetah-dir
env_type: mujoco
symbolic_env: True
action_repeat: 1
test_interval: 100
max_episode_length: 200
episodes: 50000
total_timesteps: 8000000
batch_size: 128
action_noise: 0.2
embedding_size: 20 # must = observation size when we not use enc
hidden_size: 200
belief_size: 100
state_size: 30
seed_episodes: 100
not_use_enc: True
num_tasks_sample: 10
collect_interval: 100
task_loss_type: supervised_contrastive
context_dim: 5