## cheetah-dir
envs: cheetah-dir
env_type: mujoco
symbolic_env: True
action_repeat: 1
test_interval: 100
max_episode_length: 200
episodes: 50000
total_timesteps: 8000000
batch_size: 128
action_noise: 0.2
embedding_size: 100
hidden_size: 100
belief_size: 100
state_size: 30
seed_episodes: 100
num_tasks_sample: 100
collect_interval: 1000
task_loss_type: supervised_contrastive
context_dim: 5