## cheetah-vel
envs: cheetah-vel
env_type: mujoco
symbolic_env: True
action_repeat: 1
test_interval: 100
max_episode_length: 200
episodes: 50000
total_timesteps: 6000000
batch_size: 256
action_noise: 0.3
embedding_size: 100
hidden_size: 100
belief_size: 100
state_size: 30
seed_episodes: 100
collect_interval: 5