## cheetah-vel
envs: cheetah-vel
env_type: mujoco
symbolic_env: True
action_repeat: 1
test_interval: 100
max_episode_length: 200
episodes: 50000
total_timesteps: 5000000
batch_size: 256
chunk_size: 64
action_noise: 0.2
embedding_size: 100
hidden_size: 100
belief_size: 100
state_size: 30
seed_episodes: 100
num_tasks_sample: 20
collect_interval: 500
experience_size: 10000 # 1000000 / 100 (task number)
task_loss_type: supervised_contrastive
context_dim: 40