## cheetah-vel
envs: cheetah-vel
env_type: mujoco
symbolic_env: True
action_repeat: 1
test_interval: 100
max_episode_length: 200
episodes: 50000
total_timesteps: 4000000
batch_size: 256
chunk_size: 64
action_noise: 0.2
embedding_size: 100
hidden_size: 100
belief_size: 100
state_size: 30
seed_episodes: 100
num_tasks_sample: 10
collect_interval: 100
#model_learning_rate: 0.0001
task_loss_type: supervised_contrastive
#not_use_enc: True
context_dim: 20