## humanoid-dir
envs: humanoid-dir
env_type: mujoco
symbolic_env: True
action_repeat: 1
test_interval: 100
max_episode_length: 200
episodes: 50000
total_timesteps: 500000
batch_size: 128
chunk_size: 20
action_noise: 0.1
embedding_size: 500
hidden_size: 200
belief_size: 200
state_size: 60
seed_episodes: 1000
num_tasks_sample: 10
collect_interval: 100
task_loss_type: supervised_contrastive
context_dim: 40