## humanoid-dir
envs: humanoid-dir
env_type: mujoco
symbolic_env: True
action_repeat: 1
test_interval: 100
max_episode_length: 200
episodes: 50000
total_timesteps: 1000000
batch_size: 128
action_noise: 0.3
embedding_size: 150
hidden_size: 150
belief_size: 150
state_size: 100
seed_episodes: 1000
collect_interval: 5